"""Initial migration

Revision ID: 3b3250e2a60b
Revises: 
Create Date: 2024-09-07 20:40:30.172520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3250e2a60b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('veg_week_1_2_start', sa.DateTime(), nullable=False),
    sa.Column('veg_week_1_2_end', sa.DateTime(), nullable=False),
    sa.Column('veg_week_3_start', sa.DateTime(), nullable=False),
    sa.Column('veg_week_3_end', sa.DateTime(), nullable=False),
    sa.Column('flower_week_1_3_start', sa.DateTime(), nullable=False),
    sa.Column('flower_week_1_3_end', sa.DateTime(), nullable=False),
    sa.Column('flower_week_4_6_5_start', sa.DateTime(), nullable=False),
    sa.Column('flower_week_4_6_5_end', sa.DateTime(), nullable=False),
    sa.Column('flower_week_6_5_8_5_start', sa.DateTime(), nullable=False),
    sa.Column('flower_week_6_5_8_5_end', sa.DateTime(), nullable=False),
    sa.Column('flower_week_8_5_plus_start', sa.DateTime(), nullable=False),
    sa.Column('flower_week_8_5_plus_end', sa.DateTime(), nullable=False),
    sa.Column('harvest_date', sa.DateTime(), nullable=False),
    sa.Column('drying_start', sa.DateTime(), nullable=False),
    sa.Column('drying_end', sa.DateTime(), nullable=False),
    sa.Column('curing_start', sa.DateTime(), nullable=False),
    sa.Column('curing_end', sa.DateTime(), nullable=False),
    sa.Column('yield_amount', sa.Float(), nullable=False),
    sa.Column('thc_level', sa.Float(), nullable=False),
    sa.Column('terpene_profile', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('co2_level', sa.Float(), nullable=False),
    sa.Column('light_intensity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrient_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('nitrogen_level', sa.Float(), nullable=False),
    sa.Column('phosphorus_level', sa.Float(), nullable=False),
    sa.Column('potassium_level', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrient_data')
    op.drop_table('environmental_data')
    op.drop_table('batch_data')
    # ### end Alembic commands ###
