"""Add CultivationSchedule and ProcessingSchedule models

Revision ID: 8fabd2646341
Revises: f4d03892ce7b
Create Date: 2024-09-07 21:55:56.103664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fabd2646341'
down_revision = 'f4d03892ce7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivation_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_data.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_data.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plant_maintenance_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_maintenance_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('scheduled_date', sa.DATETIME(), nullable=False),
    sa.Column('completed_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_data.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('processing_schedule')
    op.drop_table('cultivation_schedule')
    # ### end Alembic commands ###
