"""Update models to latest version

Revision ID: d7e54bf8970b
Revises: 8fabd2646341
Create Date: 2024-09-08 12:06:23.421423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e54bf8970b'
down_revision = '8fabd2646341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('environmental_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vpd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('light_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_day', sa.Boolean(), nullable=True))
        batch_op.drop_column('light_intensity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('light_intensity', sa.FLOAT(), nullable=True))
        batch_op.drop_column('is_day')
        batch_op.drop_column('light_duration')
        batch_op.drop_column('vpd')

    with op.batch_alter_table('batch_data', schema=None) as batch_op:
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
