"""Add PlantMaintenanceTask model

Revision ID: f4d03892ce7b
Revises: 3b3250e2a60b
Create Date: 2024-09-07 20:48:25.124967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d03892ce7b'
down_revision = '3b3250e2a60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_maintenance_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_data.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_data', schema=None) as batch_op:
        batch_op.alter_column('veg_week_1_2_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('veg_week_1_2_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('veg_week_3_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('veg_week_3_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_1_3_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_1_3_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_4_6_5_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_4_6_5_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_6_5_8_5_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_6_5_8_5_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_8_5_plus_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flower_week_8_5_plus_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('harvest_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('drying_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('drying_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('curing_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('curing_end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('yield_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('thc_level',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('terpene_profile',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_data', schema=None) as batch_op:
        batch_op.alter_column('terpene_profile',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('thc_level',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('yield_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('curing_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('curing_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('drying_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('drying_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('harvest_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_8_5_plus_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_8_5_plus_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_6_5_8_5_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_6_5_8_5_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_4_6_5_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_4_6_5_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_1_3_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flower_week_1_3_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('veg_week_3_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('veg_week_3_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('veg_week_1_2_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('veg_week_1_2_start',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.drop_table('plant_maintenance_task')
    # ### end Alembic commands ###
